language: scala
sudo: false

matrix:
  include:
    - scala: 2.13.3
      jdk: openjdk8
      script: sbt scalafmtSbtCheck scalafmtCheckAll

    - scala: 2.13.3
      jdk: openjdk8
      script:
        - >
          sbt
          coverage
          "++$TRAVIS_SCALA_VERSION test"
          coverageReport
          coverageAggregate
          "++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - scala: 2.12.12
      jdk: openjdk8
      script:
        - >
          sbt
          "++$TRAVIS_SCALA_VERSION test"
          "++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues"

    - scala: 2.11.12
      jdk: openjdk8
      script:
        - >
          sbt
          "++$TRAVIS_SCALA_VERSION test"
          "++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues"

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache
    - $HOME/.cache/coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delet

notifications:
  email:
    - flatmap-squad@spotify.com
